name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    # Select Xcode version
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    # Install mint
    - name: Install mint
      run: brew install mint
    - name: Cache Mint package
      uses: actions/cache@v1
      with:
            path: /usr/local/lib/mint
            key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
            restore-keys: |
              ${{ runner.os }}-mint-
      # Run build
    - name: Build
      run: xcodebuild
            -sdk iphonesimulator
            -configuration Debug
            -scheme Swift-github-actions
            build
      # Run unit test
    - name: Run tests
      run: xcodebuild
            -scheme Swift-github-actions
            -sdk iphonesimulator
            -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
            clean test
